<?php

namespace Packt\HelloWorld\Block;

use Magento\Framework\View\Element\Template;

class Landingspage extends Template
{
    public function __construct(Template\Context $context, array $data = [])
    {
        parent::__construct($context, $data);
    }

    public function getLandingsUrl()
    {
        return $this->getUrl('helloworld');
    }

    public function getRedirectUrl()
    {
        return $this->getUrl('helloworld/index/redirect');
    }

    protected function _toHtml()
    {
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}
