<?php

namespace Magenest\Movie\Block\System\Config\Form\Field;

class Disable extends \Magento\Config\Block\System\Config\Form\Field
{
    public function _getElementHtml(\Magento\Framework\Data\Form\Element\AbstractElement $element)
    {
        $element->setData('ReadOnly','true');
        return $element->getElementHtml();
        //return parent::_getElementHtml($element); // TODO: Change the autogenerated stub
    }

}